# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'BigDeal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BigDeal
  pod 'SnapKit', '~> 5.0.0'
  
  pod 'SwiftLint', '~> 0.46.2'

  pod 'IQKeyboardManagerSwift'

  target 'BigDealTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BigDealUITests' do
    # Pods for testing
  end

end
